version: '3.1'

services:
  node:
    build:
      context: .
      dockerfile: node.dockerfile
    working_dir: /src
    volumes:
      - ./src:/src
      - ./gitconfig:/home/node/.gitconfig
    tty: true
    stdin_open: true
    expose:
      - 3000
    ports:
      - 80:3000

  web:
    image: nginx:1.14
    working_dir: /src
    volumes:
      - ./src:/src
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 81:81
    links:
      - node
